# - This is the build pipeline to build and push the automated test docker image to ACR 

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build and Push image
  jobs:  
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
       - task: CmdLine@2
         displayName: 'Build and Push Image'
         inputs:
            script: |
              docker build -t testdigitalshopify:latest .
              docker save --output testdigitalshopify-latest.tar testdigitalshopify:latest
             # docker login $(acrRegistry) --username $(acrusername) --password $(azureACRToken)
             # docker tag testdigitalshopify $(acrRegistry)/testdigitalshopify
             # docker push $(acrRegistry)/testdigitalshopify  
      # - task: Docker@2
      #   inputs:
      #     containerRegistry: 'acr'
      #     repository: 'postbuildqa/maven-cucumber'
      #     command: 'buildAndPush'
      #     Dockerfile: '**/Dockerfile'
           
       - task: CopyFiles@2
         inputs:
           Contents: 'testdigitalshopify-latest.tar'
           TargetFolder: '$(Build.ArtifactStagingDirectory)'
           
       - task: PublishBuildArtifacts@1
         inputs:
           PathtoPublish: '$(Build.ArtifactStagingDirectory)'
           ArtifactName: 'drop'
           publishLocation: 'Container'
      
