jobs:
- job: DEPLOYMENT
  pool:
   vmImage: 'ubuntu-latest'
  variables:
    backendPublicIP: $(publicIP)
    privateIP: 10.0.0.6
    region: South India
    bucket: Temp
  steps:
  - script: |
      curl -s --connect-timeout 8 -d "{\"privateIP\":\"$(privateIP)\",\"publicIP\":\"$(backendPublicIP)\",\"region\":\"$(region)\",\"bucket\":\"$(bucket)\"}"   -H 'Content-Type:application/json' http://$(backendPublicIP):3337/api/v1/aws_dashboard_report/secrets/update || true  
      az login --service-principal -u $(userkey) -p $(secretkey) --tenant $(tenantkey)
      az vm run-command invoke -g WorkshopCLIResources -n WorkshopVMCLI --command-id RunShellScript --scripts "docker login azureworkshopregistry.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password $(azureACRToken)"
      az vm run-command invoke -g WorkshopCLIResources -n WorkshopVMCLI --command-id RunShellScript --scripts "docker run --name mythicalmysfitsfrontend -p 3000:3000 -p 8180:8180 --rm -i -t -d azureworkshopregistry.azurecr.io/mythicalmysfits:latest"
      az vm run-command invoke -g WorkshopCLIResources -n WorkshopVMCLI --command-id RunShellScript --scripts "docker exec -d -e REACT_APP_API=$(backendPublicIP) mythicalmysfitsfrontend npm start"
    displayName: 'Deploying To Virtual Machine'
  
- job: SMOKE_TEST
  pool:
   vmImage: 'ubuntu-latest'
  variables:
    backendPublicIP: $(publicIP)
    privateIP: 10.0.0.6
    region: South India
    bucket: Temp
  steps:
  - script: |
      curl -s --connect-timeout 8 -d "{\"privateIP\":\"$(privateIP)\",\"publicIP\":\"$(backendPublicIP)\",\"region\":\"$(region)\",\"bucket\":\"$(bucket)\"}"   -H 'Content-Type:application/json' http://$(backendPublicIP):3337/api/v1/aws_dashboard_report/secrets/update || true  
      export backendPrivateIP=$(backendPublicIP)
      export publicIP=$(backendPublicIP)
      mvn clean test -Dcucumber.options="--tags @Smoke" -DExecutionPlatform="AWS_CHROME"
    displayName: 'Smoke Test'
  dependsOn: DEPLOYMENT
  condition: succeeded()